#pragma once

#define IDI_ORBITLAN 101

#define IDR_PAYLOAD_UI 201
#define IDR_PAYLOAD_SERVICE 202
#define IDR_PAYLOAD_ENGINE 203
#define IDR_PAYLOAD_EARTH 204
#define IDR_PAYLOAD_HEADER_EARTH 205
#define IDR_PAYLOAD_DEVCON 206
#define IDR_PAYLOAD_DRIVER_INF 207
#define IDR_PAYLOAD_DRIVER_CAT 208
#define IDR_PAYLOAD_DRIVER_SYS 209
#define IDR_PAYLOAD_LICENSE_GPL 210
#define IDR_PAYLOAD_LICENSE_MS 211
